### ISSUE TITLE
Use the same file

### ISSUE THREAD

**Issue by felexkemboi** [moreen24/flask-tutorials-point#2]
Just copy the new url created in dynamics.py then put it in hello.py file. There is no need of having very many files and you are achieving the same thing 

`from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
   return "Hello World"

@app.route('/home')
def home():
   return "This is home"

@app.route('/produts<name>')
def get_products(name):
    return "the product name is " + str(name)

@app.route('/create/<first_name>/<last_name>')
def create(first_name=None,last_name=None):
    return 'hello' + first_name +","+ last_name 

if __name__ == '__main__':
   app.run()`

**Comment by felexkemboi** [comment]
the source code above should be the contents of hello.py file then delete dynamic.py

**Comment by moreen24** [comment]
done

**Comment by felexkemboi** [comment]
I am closing this issue since it is done,good job
